
# These are the services that we will be providing status updates for.

connect:
  name: 'Connect'
  url: 'connect.telvue.com'

cloudcast:
  name: 'CloudCast'
  url: 'cloudcast.telvue.com'

player:
  name: 'CloudCast Video Player'
  url: 'cloudcast.telvue.com'
